version: "3"

services:
  backend:
    container_name: backend
    build:
      context: ./worl-music-server
      dockerfile: Dockerfile
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./worl-music-server/src:/app/src
    ports:
      - 5555:5000

  mongo:
    image: mongo
    container_name: mongo
    restart: on-failure
    ports:
      - 27018:27017
    command: mongod
    volumes:
      - ./mongo-db:/data/db

  db:
    image: postgres
    container_name: db
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
